### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by nikitagitbetter** [kazuyaujihara/NCDK#11]
Hi, I am student(sorry for my english). Your NCDK library is great, I am using it for my little school project. I need to highlight one atom in molecule, but I didnt find this function in your library or sometthing like this, I used AtomContainer for molecule and DepictionGenerator for enter it. Can you help with  highlighting one atom in molecule please?

**Comment by nikitagitbetter** [comment]
Or how can I show chiral atom?

**Comment by k-ujihara** [comment]
Use NCDK.Depict.DepictionGenerator.Depiction Depict(IAtomContainer mol, IReadOnlyDictionary<IChemObject, Color> highlight = null) Method.

The sample code for MolViewer is in the following branch.
https://github.com/kazuyaujihara/NCDK/tree/25ca60eeb1ce47d8d54b7e9fc1a5bb8afa516165

<img width="535" alt="untitled" src="https://user-images.githubusercontent.com/18364688/48071811-7daa2900-e21e-11e8-90aa-c7a0ce0b6b73.png">

**Comment by nikitagitbetter** [comment]
Thank you!

вт, 6 нояб. 2018 г. в 16:39, Kazuya Ujihara <notifications@github.com>:
