### ISSUE TITLE
AtomPairs2D Fingerprint fail

### ISSUE THREAD

**Issue by ghost** [kazuyaujihara/NCDK#13]
Using NCDK Nuget Package 1.5.2 on .Net Core 

> Example 1
> 
> BuildMoleculeSimilarityAtomPairs2D Threw Exception:The given key '1_N_C' was not present in the dictionary.
> Stack: 0, File: , Method: Void ThrowKeyNotFoundException[T](T)
> Stack: 1, File: , Method: TValue get_Item(TKey), Line Number
> Stack: 2, File: , Method: NCDK.Fingerprints.IBitFingerprint GetBitFingerprint(NCDK.IAtomContainer)
> 
> Example 2
> 
> BuildMoleculeSimilarityAtomPairs2D Threw Exception:The given key '1_O_C' was not present in the dictionary.
> 
> Stack: 0, File: , Method: Void ThrowKeyNotFoundException[T](T)
> Stack: 1, File: , Method: TValue get_Item(TKey)
> Stack: 2, File: , Method: NCDK.Fingerprints.IBitFingerprint GetBitFingerprint(NCDK.IAtomContainer)

Note: Lingo and Circular Fingerprints from Nuget NCDK 1.5.2 working fine

**Comment by k-ujihara** [comment]
Thank you for your post. 
Please let me know the code to reproduce.

**Comment by k-ujihara** [comment]
I found the problem. I will fix it soon.

**Comment by k-ujihara** [comment]
This is fixed in https://github.com/kazuyaujihara/NCDK/commit/0217bb97d529230da1946db545531caa02a031b8, and uploaded to NuGet as 1.5.3-alpha.
