### ISSUE TITLE
Please add Bond Display property

### ISSUE THREAD

**Issue by Frankr0** [kazuyaujihara/NCDK#19]
There is a Enum named IBond.Display in CDK controlling how bonds appear in a 2D depiction.
But I can not find it in NCDK.

**Comment by k-ujihara** [comment]
It is BondDisplay.
https://github.com/kazuyaujihara/NCDK/blob/master/NCDK/BondDisplay.cs
(C#'s interface cannot have any subclass.)

**Comment by Frankr0** [comment]
thanks!
