### ISSUE TITLE
BondOrder was wrong parsed  from a CML File

### ISSUE THREAD

**Issue by Frankr0** [kazuyaujihara/NCDK#20]
BondOrder.Unset seems to be parsed as BondOrder.Single when using CMLReader to read a CML File.

the code `<scalar dictRef="cdk:bondOrder" title="order" dataType="xsd:integer">0</scalar>` looks not be parsed correct.

**Comment by k-ujihara** [comment]
Please post the simple code to read cml and the cml and what is the correct parsed object.

**Comment by Frankr0** [comment]
```
public void test()
{
	IAtomContainer container = new AtomContainer();
	container.Add(new Atom("C"));
	container.Add(new Atom("C"));
	container.Add(new Bond(container.Atoms[0], container.Atoms[1], BondOrder.Unset));

	using (var file = new FileStream("./cml.txt", FileMode.Create, FileAccess.Write))
	{
		using (var writer = new CMLWriter(file))
		{
			writer.Write(container);
		}
	}

	using(var cmlFile = new FileStream("./cml.txt", FileMode.Open, FileAccess.Read))
	{
		CMLReader reader = new CMLReader(cmlFile);
		var chemFile = reader.Read(new ChemFile());
		Console.WriteLine(chemFile[0][0].MoleculeSet[0].Bonds[0].Order);
	}
}
```

The output is Single but it should be Unset. 
Please have a look. thanks! @kazuyaujihara

**Comment by k-ujihara** [comment]
I consider this issue and I researched how do other tools treat it. For example, PerkinElmer ChemDraw treats the bond as single.
However I believe it should be fixed for `BondOrder.Quadruple` among others even if this attribute is CDK's original tag. I will fix it.

**Comment by Frankr0** [comment]
If read as `BondOrder.Quadruple`, An Aromatic bond would display as a dash bond. I thought the render logic may have to changed. : )

NCDK.Display/Renderers/Generators/Standards/StandardBondGenerator.cs : 210
``` C#
if (bond.IsAromatic && order.IsUnset())
{
	if (donutGenerator.IsDelocalised(bond))
		elem = GenerateSingleBond(bond, atom1, atom2);
	else
		elem = GenerateDoubleBond(bond, true);
}
else
{
	// bond orders > 3 not supported
	elem = GenerateDashedBond(atom1, atom2);
}
```

**Comment by k-ujihara** [comment]
I fixed this at commit https://github.com/kazuyaujihara/NCDK/commit/e1dbd816999c6c007fabc21363a20e21f050e315. Please check it out.

**Comment by Frankr0** [comment]
It seems good for me, thanks!
