### ISSUE TITLE
Add an Example for ProteinPocketFinder Constructor (IBioPolymer, Double[][][])

### ISSUE THREAD

**Issue by econtreras88** [kazuyaujihara/NCDK#25]
Please add an example for ProteinPocketFinder Constructor (IBioPolymer, Double[][][]).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://kazuyaujihara.github.io/NCDK/html/M_NCDK_Proteins_ProteinPocketFinder__ctor.htm

**Comment by k-ujihara** [comment]
Sorry I don't know how to use it.

**Comment by k-ujihara** [comment]
I will remove this class.
