### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by greatlse** [kazuyaujihara/NCDK#3]
when I want to build the NCDK solution, many syntax errors appeared.

my build env:
vs 2015
win7 os

like：
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1003	Syntax error, ',' expected	NCDK	D:\program\NCDK\NCDK\Beam\Core\AtomImpl.cs	123	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1026	) expected	NCDK	D:\program\NCDK\NCDK\Beam\Core\Configuration.tt.cs	372	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1003	Syntax error, ',' expected	NCDK	D:\program\NCDK\NCDK\Beam\Core\Element.cs	605	Active

so, how to fix these errors? 
Thank you very much.

**Comment by k-ujihara** [comment]
NCDK is written in C# 7 not in C# 6. It means Visual Studio 2017 is required to compile it.

C# 7 can be used on Visual Studio 2015 by replacing compiler but I don't know well.  
[How to use c#7 with Visual Studio 2015?](https://stackoverflow.com/questions/39461407/how-to-use-c7-with-visual-studio-2015)
