### ISSUE TITLE
Is it possible to put NCDK to NuGet Package Manager？

### ISSUE THREAD

**Issue by greatlse** [kazuyaujihara/NCDK#4]
It will be awesome if you put NCDK into NuGet?
It is easy to do this?

**Comment by k-ujihara** [comment]
It may be easy to do it, but I am not familiar with NuGet. 
It is pleasing that someone will make it or consult us.

**Comment by k-ujihara** [comment]
NuGet packages of NCDK are uploaded at the followings.
https://www.nuget.org/packages/NCDK/1.3.0
https://www.nuget.org/packages/NCDK.Display/1.3.0

**Comment by greatlse** [comment]
Thanks very much
