### ISSUE TITLE
TemplateHandler3D issue

### ISSUE THREAD

**Issue by ivok2002** [kazuyaujihara/NCDK#5]
Greetings,

I found an issue with the templateHandler logic and I will appreciate if you could support me on that one.

File: TemplateHandler3D.cs
Line: 227

The warning pop-ups every time on generating 3D ring coordinates which seems a little bit weird.
So I was thinking is it possible to be a bug?

Original code:

            if (best != null)
            {
                AssignCoords(best, bestMap);
            }
            else if (secondBest != null)
            {
                AssignCoords(secondBest, secondBestMap);
            }

            Console.Error.WriteLine("WARNING: Maybe RingTemplateError!");

Shouldn't it be something like that:

            if (best != null)
            {
                AssignCoords(best, bestMap);
            }
            else if (secondBest != null)
            {
                AssignCoords(secondBest, secondBestMap);
            }
            else
            {
            Console.Error.WriteLine("WARNING: Maybe RingTemplateError!");
            }

Or even that one (showing warning if there is no primal best make sense too):

            if (best != null)
            {
                AssignCoords(best, bestMap);
            }
            else if (secondBest != null)
            {
                AssignCoords(secondBest, secondBestMap);

                Console.Error.WriteLine("WARNING: Maybe RingTemplateError!");
            }

**Comment by k-ujihara** [comment]
This is fixed in 3421fb4e171519813d0b21c373aaadac5e1ddf7d.
Thank you.
