### ISSUE TITLE
VABCDescriptor

### ISSUE THREAD

**Issue by ghost** [kazuyaujihara/NCDK#7]
Are there any known problems with the ABCVolume descriptor calculation? Using different Smiles, I get a System.ArgumentNullException error at NCDK.Config.GetAtomType(string identifier) where identifier is the null parameter. Shows up when using the Descriptor Engine for all at once, or when running descriptor calculation one by one. All other descriptor calculators so far seen to work OK.

**Comment by k-ujihara** [comment]
Dear Sir, 
You need to call AtomContainerManipulator.PercieveAtomTypesAndConfigureAtoms(molecule) before call VABCVolume.Calculate(molecule) method despite calling Aromaticity.CDKLegacy.Apply(molecule) in the method. Some APIs in cdk are still complex and not intuitive.

**Comment by ghost** [comment]
Many thanks. VABCVolume now calculating correctly. Appreciate the quick answer
