### ISSUE TITLE
Estate not closing files?

### ISSUE THREAD

**Issue by ghost** [kazuyaujihara/NCDK#8]
We are getting errors running between 80-100 molecules through the fingerprint calculation. The error is a system error "Unhandled exception. System.IO.IO.Exception: too many files open". 

We can run Lingo and the substructure based fingerprint without seeing the problem so it seems to be specific to Estate. We are running with NCDK on .Net Core and Centos 7. Has anyone else seen this or similar? Any suggestions for us to investigate further would be welcome.

**Comment by k-ujihara** [comment]
Please let me know the code to make exception.

**Comment by ghost** [comment]
The error does not reproduce outside our framework. Will close.
